Repository lgdlong/dev-wiki, pull requests merged in 2025-08, with the labels that each got.

#29 Feat/add-duration-and-uploader-id-for-videos
  .github/copilot-instructions.md
  apps/api/.env.development
  apps/api/nest-cli.json
  apps/api/package.json
  apps/api/src/account/dto/update-account.dto.ts
  apps/api/src/app.module.ts
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/auth/google.strategy.ts
  apps/api/src/main.ts
  apps/api/src/mappers/video.mapper.ts
  apps/api/src/types/express/index.d.ts
  apps/api/src/videos/dto/create-video.dto.ts
  apps/api/src/videos/entities/video.entity.ts
  apps/api/src/videos/interfaces/request-create-video.interface.ts
  apps/api/src/videos/interfaces/youtube-metadata.interface.ts
  apps/api/src/videos/videos.controller.ts
  apps/api/src/videos/videos.service.ts
  apps/db/README.md
  apps/db/dump-dev_wiki_local-202508110624.dump
  apps/db/sample_accounts.json
  apps/web/src/app/admin/page.tsx
  apps/web/src/app/mod/youtube/constant/index.ts
  apps/web/src/app/mod/youtube/post-video/PostVideoForm.tsx
  apps/web/src/components/Navbar.tsx
  apps/web/src/middleware.ts
  apps/web/src/types/video.ts
  apps/web/src/utils/api/auth.ts
  apps/web/src/utils/api/categories.ts
  apps/web/src/utils/api/video.ts
  apps/web/src/utils/jwt.ts
  apps/web/src/validations/post-video-schema.ts
  docker-compose.yml
  pnpm-lock.yaml
Labels: bug, enhancement, Possible security concern, Review effort 3/5

#34 feat/redirect-base-on-roles
  apps/web/package.json
  apps/web/src/app/(auth)/login/page.tsx
  apps/web/src/app/(dashboard)/mod/page.tsx
  apps/web/src/components/ui/table.tsx
  apps/web/src/components/ui/tabs.tsx
  pnpm-lock.yaml
Labels: enhancement, Review effort 4/5, Possible security concern

#40 39-fix-ui-in-mod-youtube-edit
  apps/web/src/app/(dashboard)/mod/youtube/manage-videos/[id]/edit/page.tsx
  apps/web/src/components/videos/VideoInfoCard.tsx
Labels: Possible security concern, ui, Review effort 5/5

#42 41-block-mod-go-to-guest-pase
  apps/web/src/middleware.ts
Labels: bug, Review effort 2/5, Possible security concern

#50 feat(ui): add Dashboard link to mod sidebar navigation
  apps/web/src/components/mod-sidebar.tsx
Labels: Review effort 1/5, ui

#56 Feat/create post composer
  apps/api/src/app.module.ts
  apps/api/src/core/decorators/get-user-id.decorator.ts
  apps/api/src/modules/tutorial/dto/create-tutorial.dto.ts
  apps/api/src/modules/tutorial/dto/update-tutorial.dto.ts
  apps/api/src/modules/tutorial/tutorial.controller.ts
  apps/api/src/modules/tutorial/tutorial.module.ts
  apps/api/src/modules/tutorial/tutorial.service.ts
  apps/api/src/modules/tutorials-tags/dto/create-tutorials-tag.dto.ts
  apps/api/src/modules/tutorials-tags/entities/tutorials-tag.entity.ts
  apps/api/src/modules/tutorials-tags/tutorials-tags.controller.ts
  apps/api/src/modules/tutorials-tags/tutorials-tags.module.ts
  apps/api/src/modules/tutorials-tags/tutorials-tags.service.ts
  apps/api/src/modules/tutorials/dto/create-tutorials.dto.ts
  apps/api/src/modules/tutorials/dto/update-tutorials.dto.ts
  apps/api/src/modules/tutorials/entities/tutorials.entity.ts
  apps/api/src/modules/tutorials/tutorials.controller.ts
  apps/api/src/modules/tutorials/tutorials.module.ts
  apps/api/src/modules/tutorials/tutorials.service.spec.ts
  apps/api/src/modules/tutorials/tutorials.service.ts
  apps/api/src/modules/video-tags/video-tags.controller.ts
  apps/db/dump-dev_wiki_local-202508250209.dump
  apps/web/package.json
  apps/web/src/app/(dashboard)/mod/page.tsx
  apps/web/src/app/(dashboard)/mod/products/manage-products/[id]/edit/page.tsx
  apps/web/src/app/(dashboard)/mod/products/manage-products/columns.tsx
  apps/web/src/app/(dashboard)/mod/products/manage-products/data-table.tsx
  apps/web/src/app/(dashboard)/mod/products/manage-products/page.tsx
  apps/web/src/app/(dashboard)/mod/products/new/page.tsx
  apps/web/src/app/(dashboard)/mod/tutorials/manage-tutorials/page.tsx
  apps/web/src/app/(dashboard)/mod/tutorials/new/page.tsx
  apps/web/src/app/(dashboard)/mod/youtube/manage-videos/[id]/edit/page.tsx
  apps/web/src/components/mod-sidebar.tsx
  apps/web/src/components/tutorials/tutorial-composer.tsx
  apps/web/src/components/tutorials/tutorial-markdown.tsx
  apps/web/src/components/ui/announce-success-toast.tsx
  apps/web/src/components/ui/textarea.tsx
  apps/web/src/components/ui/top-banner.tsx
  apps/web/src/middleware.ts
  apps/web/src/types/product.ts
  apps/web/src/types/tutorial.ts
  apps/web/src/utils/api/productApi.ts
  apps/web/src/utils/api/tutorial.ts
  apps/web/src/validations/post.ts
  package.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#61 Integrate bulk category assignment and enhance category management features
  Makefile
  apps/api/src/modules/categories/categories.controller.ts
  apps/api/src/modules/product-categories/dto/assign-categories.dto.ts
  apps/api/src/modules/product-categories/product-categories.controller.ts
  apps/api/src/modules/product-categories/product-categories.service.ts
  apps/web/example.test.ts
  apps/web/package.json
  apps/web/src/app/(dashboard)/mod/categories/_components/category-dialog.tsx
  apps/web/src/app/(dashboard)/mod/categories/_components/category-table.tsx
  apps/web/src/app/(dashboard)/mod/categories/_components/columns.tsx
  apps/web/src/app/(dashboard)/mod/categories/page.tsx
  apps/web/src/app/(dashboard)/mod/products/[id]/edit/_components/EditProductCategoryForm.tsx
  apps/web/src/app/(dashboard)/mod/products/[id]/edit/page.tsx
  apps/web/src/app/(dashboard)/mod/products/manage-products/[id]/edit/page.tsx
  apps/web/src/app/(dashboard)/mod/products/manage-products/_components/columns.tsx
  apps/web/src/app/(dashboard)/mod/products/manage-products/_components/data-table.tsx
  apps/web/src/app/(dashboard)/mod/products/manage-products/page.tsx
  apps/web/src/components/mod-sidebar.tsx
  apps/web/src/components/ui/dialog.tsx
  apps/web/src/components/ui/select.tsx
  apps/web/src/types/product-categories.ts
  apps/web/src/utils/api/categories.ts
  apps/web/src/utils/api/productApi.ts
  apps/web/src/utils/auth.ts
  apps/web/src/utils/category.ts
  apps/web/src/validations/edit-product-category-schema.ts
  pnpm-lock.yaml
Labels: bug, Possible security concern, feature, ui, Review effort 5/5

#65 Feat/video tags
  apps/web/package.json
  apps/web/src/app/(dashboard)/mod/youtube/manage-videos/[id]/edit/page.tsx
  apps/web/src/hooks/useTagSearch.ts
  apps/web/src/utils/api/tagApi.ts
  apps/web/src/utils/api/videoApi.ts
  pnpm-lock.yaml
Labels: Review effort 2/5
