Repository lgdlong/dev-wiki, pull requests merged in 2025-09, with the labels that each got.

#69 Style/manage admin UI/ux
  apps/db/init.sh
  apps/web/package.json
  apps/web/src/app/(dashboard)/admin/layout.tsx
  apps/web/src/app/(dashboard)/admin/page.tsx
  apps/web/src/components/admin-sidebar.tsx
Labels: Review effort 3/5, Style UI/UX

#72 chore(db): solve CRLF and LF newline issues in init.sh, change tutorial slug to varchar(255)
  apps/db/dump-dev_wiki_local-202509070232.dump
  apps/db/init.sh
Labels: Review effort 1/5

#76 #75 Add support for tutorial tags and enhance related features
  apps/api/src/modules/tutorials/dto/tutorials.dto.ts
  apps/api/src/modules/tutorials/mappers/tutorials.mapper.ts
  apps/api/src/modules/tutorials/tutorials.module.ts
  apps/api/src/modules/tutorials/tutorials.service.ts
  apps/api/src/shared/constants.ts
  apps/db/dump-dev_wiki_local-202509071219.dump
  apps/db/init.sh
  apps/web/src/app/(public)/tutorials/[slug]/page.tsx
  apps/web/src/app/(public)/tutorials/_components/TutorialsIndex.tsx
  apps/web/src/config/constants.ts
  apps/web/src/types/tag.ts
  apps/web/src/types/tutorial.ts
  apps/web/src/utils/api/auth.ts
Labels: Possible security concern, Review effort 5/5
